import "./globals.css";
import type { Metadata } from "next";
import { fonts } from "./fonts";
import Providers from "@/lib/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={fonts.inter.className}>{children}</body>
      </html>
    </Providers>
  );
}
